catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import CategoryListView, ContactCreateView, ProductsListView, ProductsDetailView, ProductsCreatView, \
    ProductsUpdateView, ProductsDeleteView, BlogsListView, BlogsDetailView, BlogCreateView, BlogUpdateView, \
    BlogsDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('products/', cache_page(60)(ProductsListView.as_view()), name='products'),  # закеширование всего контроллера
    path('product_details/<int:pk>/', ProductsDetailView.as_view(), name='product_details'),
    path('products/create/', ProductsCreatView.as_view(), name='products_create'),
    path('products/update/<int:pk>/', ProductsUpdateView.as_view(), name='products_update'),
    path('products/delete/<int:pk>/', ProductsDeleteView.as_view(), name='products_delete'),
    path('blogs/', BlogsListView.as_view(), name='blogs'),
    path('blog_details/<int:pk>/', BlogsDetailView.as_view(), name='blog_details'),
    path('blogs/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blogs/update/<int:pk>/', BlogUpdateView.as_view(), name='blogs_update'),
    path('blogs/delete/<int:pk>/', BlogsDeleteView.as_view(), name='blogs_delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileView, VerifyEmailView, RegisterView, VerifyEmailSentView, EmailConfirmedView, \
    UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordResetDoneView, UserPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<str:uidb64>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('verify_email_sent/', VerifyEmailSentView.as_view(), name='verify_email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<str:uidb64>/<str:token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete')
]

catalog/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=255)  # наименование категории
    description = models.TextField()  # писание категории

    def __str__(self):
        # Метод для отображения объектов класса Category
        # return f'{self.id}: {self.name}'
        return f'{self.name}'

    class Meta:
        verbose_name = "Category"  # наименование модели в единственном числе
        verbose_name_plural = "Categories"  # множественное число наименования модели
        ordering = ('name',)  # сортировка по имени категории


class Product(models.Model):
    name = models.CharField(max_length=255)  # наименование продукта
    description = models.TextField()  # описание продукта
    image = models.ImageField(upload_to='products/', verbose_name='image', **NULLABLE)  # изображение продукта (превью),
    # с указанием пути для
    # сохранения изображений
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # категория продукта, связь с моделью Category
    # через ForeignKey
    price = models.DecimalField(max_digits=10, decimal_places=2)  # цена продукта
    date_of_creation = models.DateTimeField(
        default=timezone.now)  # дата создания продукта, с дефолтным значением текущего
    # времени
    updated_at = models.DateTimeField(auto_now=True)  # дата последнего изменения продукта, с автоматическим
    product_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                      null=True)  # привязка к авторизованному пользователю.
    # обновлением при изменении записи
    is_published = models.BooleanField(default=False)  # признак публикации продукта

    def __str__(self):
        return f'{self.image}\n{self.name} {self.description}'

    def get_active_version(self):
        return Version.get_active_version(self)

    class Meta:
        verbose_name = "Product"  # наименование модели в единственном числе
        verbose_name_plural = "Products"  # множественное число наименования модели
        ordering = ('-date_of_creation',)  # сортировки по убыванию даты создания продукта
        permissions = [
            ("can_cancel_product_publication", "Can cancel product publication"),
            ("can_change_product_description", "Can change product description"),
            ("can_change_product_category", "Can change product category"),
        ]


class Contacts(models.Model):
    name = models.CharField(max_length=100, verbose_name="user__name")
    email = models.CharField(max_length=100, verbose_name="user_email")
    message = models.CharField(max_length=100, verbose_name="user_message")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"


class Blogs(models.Model):
    name = models.CharField(max_length=100, verbose_name="blog_name")  # заголовок
    slug = models.CharField(max_length=255)  # slug (реализовать через CharField)
    description = models.TextField(null=True, blank=True, verbose_name="blog_description")  # содержимое
    image = models.ImageField(upload_to='products/', **NULLABLE)  # превью (изображение)
    created_at = models.DateTimeField(default=timezone.now)  # дата создания
    is_published = models.BooleanField(default=True)  # признак публикации
    blog_views = models.IntegerField(verbose_name="blog_views", default=0)  # количество просмотров

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "Blog"  # наименование модели в единственном числе
        verbose_name_plural = "Blogs"  # множественное число наименования модели


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # название продукта
    version_number = models.CharField(max_length=100, verbose_name='Номер версии')  # номер версии
    version_name = models.CharField(max_length=100, verbose_name='Название версии')  # название версии
    is_current = models.BooleanField(default=False, verbose_name='Является ли версия текущей')

    def __str__(self):
        return f"{self.product} {self.version_number} ({self.version_name})"

    def save(self, *args, **kwargs):
        if self.is_current:  # Деактивируем все другие версии для данного продукта
            Version.objects.filter(product=self.product).exclude(pk=self.pk).update(is_current=False)
        super().save(*args, **kwargs)

    @classmethod
    def get_active_version(cls, product):
        try:
            return cls.objects.get(product=product, is_current=True)
        except ObjectDoesNotExist:
            return None

    class Meta:
        verbose_name = "Version"
        verbose_name_plural = "Versions"

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'recreated_at', 'product_owner')

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']  # список запрещенных слов
        for word in forbidden_words:
            # Проверяем, содержит ли название или описание запрещенное слово
            if word in name.lower() or word in description.lower():
                # Если содержит, генерируем исключение с сообщением об ошибке
                raise forms.ValidationError(f'Слово "{word}" запрещено в названии и описании продукта.')
        return cleaned_data


# Валидация в Django - это процесс проверки данных, введенных пользователем, на соответствие заданным правилам. В
# Django валидация может быть выполнена на разных уровнях, например, на уровне форм, моделей или сериализаторов

class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import HttpResponse, HttpResponseForbidden, Http404
from django.urls import reverse_lazy
from django.views import generic
from django.utils.text import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product, Contacts, Blogs, Version
from catalog.services import get_cached_product_data


class CategoryListView(generic.ListView):
    model = Category
    context_object_name = 'objects_list'
    extra_context = {
        'title': 'Список категорий продуктов'
    }


class ProductsListView(generic.ListView):
    model = Product
    context_object_name = 'objects_list'
    extra_context = {'title': 'Список продуктов'}

    def get_queryset(self):
        queryset = super().get_queryset()
        for product in queryset:
            product.description = product.description[:100]
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context['object_list']
        for product in products:
            product.get_active_version()
        return context


class ProductsDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)  # Получаем контекст данных из родительского класса
        cached_data = get_cached_product_data(self.object)
        context_data.update(cached_data)
        return context_data


class ProductsCreatView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    # permission_required = 'catalog.add_product'З

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save(commit=False)
        self.object.product_owner = self.request.user
        self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductsUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    # permission_required = 'catalog.change_product'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.product_owner != self.request.user:
            raise Http404("Вы не являетесь владельцем продукта.")
        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        if not self.request.user.has_perm('catalog.can_change_product_description'):
            return HttpResponseForbidden("You don't have permission to change product description.")
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductsDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')

    # permission_required = 'catalog.delete_product'

    def test_func(self):
        return self.request.user.is_superuser  # жесткие требования на удаление ( только суперюзер может удалить)


class ContactCreateView(generic.CreateView):
    model = Contacts
    template_name = "catalog/contact.html"
    fields = ('name', 'email', 'message')

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Наши контакты"
        return context_data


class BlogsListView(generic.ListView):
    model = Blogs
    queryset = Blogs.objects.filter(is_published=True)
    context_object_name = 'blogs'
    paginate_by = 10


class BlogsDetailView(generic.DetailView):
    model = Blogs

    def get(self, request, *args, **kwargs):
        # Получаем объект статьи
        self.object = self.get_object()
        # Увеличиваем счетчик просмотров
        self.object.blog_views += 1
        # Сохраняем изменения в базе данных
        self.object.save()
        # Вызываем метод get() родительского класса DetailView
        return super().get(request, *args, **kwargs)


class BlogCreateView(generic.CreateView):
    model = Blogs
    fields = ['name', 'slug', 'description', 'image', 'is_published', 'blog_views']
    success_url = reverse_lazy('catalog:blogs')

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.name)
        return super().form_valid(form)


class BlogUpdateView(generic.UpdateView):
    model = Blogs
    fields = ['name', 'description', 'image']
    success_url = reverse_lazy('catalog:blogs')

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('catalog:blog_details', kwargs={'pk': pk})


class BlogsDeleteView(generic.DeleteView):
    model = Blogs
    success_url = reverse_lazy('catalog:blogs')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                </div>
                {% include 'catalog/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</main>

<footer class="text-muted">
    <div class="container">
        <p> &copy; 2023 - {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blogs_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление блога</h5>
      <form method="post">
        {% csrf_token %}
        Уверены, что хотите удалить блог "{{ object.name }}"?<br>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog:blogs' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/blogs_detail.html
{% extends 'catalog/base.html' %}


{% block content %}

    <style>
        .centered-container {
            text-align: center;
        }

        .centered-container ul {
            display: inline-block;
            text-align: left;
        }
    </style>
    {% load mytags %}
    <ul>
        <h4>{{ blogs.name }}</h4>
        <img class="img-thumbnail" src="{% mediapath product.image %}" alt="Thumbnail image" width="400" height="400"/>

    </ul>
    <ul>
        <div class="centered-container">

            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p style="text-align: left;">{{ blogs.description }} </p>

                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:blogs' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        </div>
    </ul>
{% endblock %}
>

catalog/templates/catalog/blogs_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
{#                    <h1>Добавить новый продукт</h1>#}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Изменить{% else %}Добавить{% endif %}">
                </form>
                <div class="card-footer">
                    <a href="{% url 'catalog:blogs' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/blogs_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <a href="{% url 'catalog:blog_create' %}" class="btn btn-primary mb-3">Добавить блог</a>
            </div>
        </div>
        <div class="row">
            {% for object in object_list %}
                {% load mytags %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card">
                        <img class="card-img-top" src="{% mediapath object.image %}" alt="Thumbnail image">
                        <div class="card-body">
                            <h5 class="card-title"><a
                                    href="{% url 'catalog:blog_details' pk=object.id %}">{{ object.name }}</a></h5>
                            <p class="card-text">{{ object.description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'catalog:blogs_update' object.pk %}"
                                   class="btn btn-warning">Изменить</a>
                                <a href="{% url 'catalog:blogs_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'catalog:products' %}" class="btn btn-primary"><< Назад</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for object in object_list %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <p class="card-text">{{ object| title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
{#                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>#}
{#                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>#}
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    Магазин МСК<br>
                    Магазин СПБ
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post" class="contact-form">
                    {% csrf_token %}
                    <h1 class="form-header">Свяжитесь с нами!</h1>
                    <div class="form-group">
                        <input class="form-control" name="name" placeholder="Имя"/>
                    </div>
                    <div class="form-group">
                        <input class="form-control" name="email" placeholder="Email"/>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" placeholder="Сообщение"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary form-control">Отправить</button>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            color: black;
            background: url(https://img.freepik.com/premium-vector/set-healthy-food-cartoons_18591-24543.jpg?w=2000) center center;
            background-size: 35%;
            text-align: center;
            font-family: Arial, sans-serif;
        }
    </style>
</head>
<body>
  <div class="uk-container">
    <div class="uk-grid uk-child-width-1-2@m" uk-grid>
      <div>
        <h1>ДОБРО ПОЖАЛОВАТЬ!!!</h1>
        <p>ПРОДУКТЫ ПО ДОСТУПНЫМ ЦЕНАМ!!!</p>
        <p>ОТ ВЫБОРА ГЛАЗА РАЗБЕГАЮТСЯ!!!</p>
        <a href="{% url 'contact' %}" class="btn btn-primary">Чего ждем? Заходим!</a>
        <br>
        <a href="{% url 'product_detail' %}" class="btn btn-primary">Cписок товаров!</a>
      </div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for object in objects_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                     <p class="card-text"><a href="{% url 'catalog:product_details' product_id=object.id %}">{{ object.name }}</a></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
{#                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>#}
{#                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление продукта</h5>
      <form method="post">
        {% csrf_token %}
        Уверены, что хотите удалить продукт "{{ object.name }}"?<br>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog:products' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}


{% block content %}

    <style>
        .centered-container {
            text-align: center;
        }

        .centered-container ul {
            display: inline-block;
            text-align: left;
        }
    </style>
    {% load mytags %}
    <ul>
        <h4>{{ product.name }}</h4>
        <img class="img-thumbnail" src="{% mediapath product.image %}" alt="Thumbnail image" width="400" height="400"/>

    </ul>
    <ul>
        <div class="centered-container">

            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p style="text-align: left;">{{ product.description }} </p>
                    <p style="text-align: left;">Цена: {{ product.price }} руб.</p>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:products' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </ul>
{% endblock %}

catalog/templates/catalog/product_details.html
{% extends 'catalog/base.html' %}


{% block content %}

<style>
    .centered-container {
        text-align: center;
    }
    .centered-container ul {
        display: inline-block;
        text-align: left;
    }
</style>
    {% load mytags %}
    <ul>
        <h4>{{ product.name }}</h4>
        <img class="img-thumbnail" src="{% mediapath product.image %}" alt="Thumbnail image" width="400" height="400"/>

    </ul>
        <ul>
            <div class="centered-container">

              <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p style="text-align: left;">{{ product.description }} </p>
                        <p style="text-align: left;">Цена: {{ product.price }} руб.</p>
                </div>
              </div>
            </div>
        </ul>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row flex-wrap">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {#<h1>Добавить новый продукт</h1>#}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Изменить{% else %}Добавить{% endif %}">
                    </form>
                    <div class="card-footer">
                        <a href="{% url 'catalog:products' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Версия продукта
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        {% if user.is_authenticated and not request.user.is_staff %}
            <a href="{% url 'catalog:products_create' %}" class="btn btn-primary m-2">Добавить продукт</a>
        {% endif %}
    </div>
    {% for object in objects_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text"><a
                            href="{% url 'catalog:product_details' pk=object.id %}">{{ object.name }}</a></p>
                    {% if object.active_version %}
                        <p class="card-text">Активная версия: {{ object.active_version.version_name }}</p>
                    {% endif %}
                    <div class="btn-group">
                        {% if perms.catalog.change_product %}
                            <a href="{% url 'catalog:products_update' object.pk %}" class="btn btn-warning"
                               role="button">Изменить &raquo;</a>
                        {% endif %}
                        {% if user.is_superuser %}
                            <a href="{% url 'catalog:products_delete' object.pk %}" class="btn btn-danger"
                               role="button">Удалить &raquo;</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}